from __future__ import annotations

import importlib
import json
import os
import tarfile
import tempfile
import urllib.error
import urllib.parse
import urllib.request
from pathlib import Path

cache_restore = importlib.import_module("helpers.009_cache_restore")
CacheArtifact = cache_restore.CacheArtifact
_cache_ready = cache_restore._cache_ready
_github_request = cache_restore._github_request
_read_json = cache_restore._read_json


def _create_archive(source: Path, destination: Path) -> None:
    with tarfile.open(destination, "w:gz") as tar:
        for item in sorted(source.iterdir()):
            tar.add(item, arcname=item.name, recursive=True)


def _get_or_create_release(
    *,
    github_repo: str,
    release_tag: str,
    token: str,
) -> dict:
    release_url = (
        f"https://api.github.com/repos/{github_repo}/releases/tags/"
        f"{urllib.parse.quote(release_tag, safe='')}"
    )
    try:
        return _read_json(_github_request(release_url, token=token))
    except urllib.error.HTTPError as exc:
        if exc.code != 404:
            raise

    payload = json.dumps(
        {
            "tag_name": release_tag,
            "name": f"Runtime cache {release_tag}",
            "body": "Portable runtime cache seed generated by Modal.",
            "prerelease": True,
        }
    ).encode("utf-8")
    create_url = f"https://api.github.com/repos/{github_repo}/releases"
    return _read_json(
        _github_request(
            create_url,
            method="POST",
            token=token,
            data=payload,
            content_type="application/json",
        )
    )


def step_010_publish_cache(
    artifact: CacheArtifact,
    *,
    github_repo: str,
    release_tag: str,
    replace_existing: bool = False,
) -> bool:
    """把新生成的可移植缓存发布为 GitHub Release asset。"""
    if not _cache_ready(artifact):
        print(
            f"[010_CACHE_PUBLISH_SKIP] name={artifact.name} reason=cache_not_ready",
            flush=True,
        )
        return False

    token = os.environ.get("GITHUB_TOKEN", "").strip()
    if not token:
        print(
            f"[010_CACHE_PUBLISH_SKIP] name={artifact.name} reason=no_github_token",
            flush=True,
        )
        return False

    release = _get_or_create_release(
        github_repo=github_repo,
        release_tag=release_tag,
        token=token,
    )

    for asset in release.get("assets", []):
        if asset.get("name") != artifact.release_asset:
            continue
        if not replace_existing:
            print(
                f"[010_CACHE_RELEASE_HIT] name={artifact.name} "
                f"asset={artifact.release_asset}",
                flush=True,
            )
            return True
        delete_request = _github_request(
            asset["url"],
            method="DELETE",
            token=token,
        )
        with urllib.request.urlopen(delete_request, timeout=60):
            pass
        break

    source = Path(artifact.local_path)
    with tempfile.TemporaryDirectory(prefix="glm53-cache-publish-") as temp_dir:
        archive = Path(temp_dir) / artifact.release_asset
        _create_archive(source, archive)
        upload_url = release["upload_url"].split("{", 1)[0]
        query = urllib.parse.urlencode({"name": artifact.release_asset})
        request = _github_request(
            f"{upload_url}?{query}",
            method="POST",
            token=token,
            data=archive.read_bytes(),
            content_type="application/gzip",
        )
        with urllib.request.urlopen(request, timeout=600) as response:
            response.read()

    print(
        f"[010_CACHE_PUBLISHED] name={artifact.name} asset={artifact.release_asset}",
        flush=True,
    )
    return True
