from __future__ import annotations

import http.client
import importlib
import json
import os
import tarfile
import tempfile
import urllib.error
import urllib.parse
import urllib.request
from pathlib import Path

cache_restore = importlib.import_module("helpers.009_cache_restore")
CacheArtifact = cache_restore.CacheArtifact
_cache_ready = cache_restore._cache_ready
_github_request = cache_restore._github_request
_read_json = cache_restore._read_json


def _create_archive(source: Path, destination: Path) -> None:
    # Runtime caches are mostly compiled binaries; level 1 avoids wasting CPU on marginal compression.
    with tarfile.open(destination, "w:gz", compresslevel=1) as tar:
        for item in sorted(source.iterdir()):
            tar.add(item, arcname=item.name, recursive=True)


def _get_or_create_release(
    *,
    github_repo: str,
    release_tag: str,
    token: str,
) -> dict:
    release_url = (
        f"https://api.github.com/repos/{github_repo}/releases/tags/"
        f"{urllib.parse.quote(release_tag, safe='')}"
    )
    try:
        return _read_json(_github_request(release_url, token=token))
    except urllib.error.HTTPError as exc:
        if exc.code != 404:
            raise

    payload = json.dumps(
        {
            "tag_name": release_tag,
            "name": f"Runtime cache {release_tag}",
            "body": "Portable runtime cache seed generated by Modal.",
            "prerelease": True,
        }
    ).encode("utf-8")
    create_url = f"https://api.github.com/repos/{github_repo}/releases"
    return _read_json(
        _github_request(
            create_url,
            method="POST",
            token=token,
            data=payload,
            content_type="application/json",
        )
    )


def _upload_asset_streaming(
    *,
    upload_url: str,
    asset_name: str,
    archive: Path,
    token: str,
) -> None:
    parsed = urllib.parse.urlparse(upload_url)
    query = urllib.parse.urlencode({"name": asset_name})
    target = f"{parsed.path}?{query}"
    headers = {
        "Accept": "application/vnd.github+json",
        "Authorization": f"Bearer {token}",
        "Content-Type": "application/gzip",
        "Content-Length": str(archive.stat().st_size),
        "User-Agent": "modal-glm53-cache-manager",
        "X-GitHub-Api-Version": "2022-11-28",
    }
    connection = http.client.HTTPSConnection(parsed.hostname, parsed.port or 443, timeout=600)
    try:
        connection.putrequest("POST", target)
        for key, value in headers.items():
            connection.putheader(key, value)
        connection.endheaders()
        with archive.open("rb") as source:
            while chunk := source.read(8 * 1024 * 1024):
                connection.send(chunk)
        response = connection.getresponse()
        body = response.read()
        if response.status < 200 or response.status >= 300:
            raise RuntimeError(
                f"GitHub asset upload failed: status={response.status} body={body[:512]!r}"
            )
    finally:
        connection.close()


def step_010_publish_cache(
    artifact: CacheArtifact,
    *,
    github_repo: str,
    release_tag: str,
    replace_existing: bool = False,
) -> bool:
    """把新生成的可移植缓存发布为 GitHub Release asset。"""
    if not _cache_ready(artifact):
        print(
            f"[010_CACHE_PUBLISH_SKIP] name={artifact.name} reason=cache_not_ready",
            flush=True,
        )
        return False

    token = os.environ.get("GITHUB_TOKEN", "").strip()
    if not token:
        print(
            f"[010_CACHE_PUBLISH_SKIP] name={artifact.name} reason=no_github_token",
            flush=True,
        )
        return False

    release = _get_or_create_release(
        github_repo=github_repo,
        release_tag=release_tag,
        token=token,
    )

    for asset in release.get("assets", []):
        if asset.get("name") != artifact.release_asset:
            continue
        if not replace_existing:
            print(
                f"[010_CACHE_RELEASE_HIT] name={artifact.name} "
                f"asset={artifact.release_asset}",
                flush=True,
            )
            return True
        delete_request = _github_request(
            asset["url"],
            method="DELETE",
            token=token,
        )
        with urllib.request.urlopen(delete_request, timeout=60):
            pass
        break

    source = Path(artifact.local_path)
    with tempfile.TemporaryDirectory(prefix="glm53-cache-publish-") as temp_dir:
        archive = Path(temp_dir) / artifact.release_asset
        _create_archive(source, archive)
        upload_url = release["upload_url"].split("{", 1)[0]
        _upload_asset_streaming(
            upload_url=upload_url,
            asset_name=artifact.release_asset,
            archive=archive,
            token=token,
        )

    print(
        f"[010_CACHE_PUBLISHED] name={artifact.name} asset={artifact.release_asset}",
        flush=True,
    )
    return True
